{
 "title": "Lustre and HSM",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Usage on Disk (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/lustre" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "ondemand" }
     ]
    }
   ]
  },
  {
   "title": "Lustre Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load1\") AS \"Load1\" FROM \"system\" WHERE (\"host\" =~ /lustre/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lhsm",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "volume" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre HSM Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lhsm",
     "select": [
      [
       { "params": [ "volume" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre Usage By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lustre",
     "select": [
      [
       { "params": [ "volume" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Files",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lhsm",
     "query": "SELECT last(\"count\") FROM \"lhsm\" WHERE $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lustre Metadata",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lustre2",
     "query": "SELECT difference(mean(\"unlink\")) AS \"unlink\", difference(mean(\"close\")) AS \"close\", difference(mean(\"getattr\")) AS \"getattr\", difference(mean(\"getxattr\")) AS \"getxattr\", difference(mean(\"link\")) AS \"link\", difference(mean(\"mkdir\")) AS \"mkdir\", difference(mean(\"setxattr\")) AS \"setxattr\", difference(mean(\"open\")) AS \"open\", difference(mean(\"rename\")) AS \"rename\", difference(mean(\"rmdir\")) AS \"rmdir\", difference(mean(\"mknod\")) AS \"mknod\", difference(mean(\"setattr\")) AS \"setattr\", difference(mean(\"statfs\")) AS \"statfs\", difference(mean(\"setxattr\")) AS \"setxattr\", difference(mean(\"sync\")) AS \"sync\" FROM \"lustre2\" WHERE (\"host\" = 'mds1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unlink" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "unlink" ], "type": "alias" }
      ],
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "close" ], "type": "alias" }
      ],
      [
       { "params": [ "getattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "getattr" ], "type": "alias" }
      ],
      [
       { "params": [ "getxattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "getxattr" ], "type": "alias" }
      ],
      [
       { "params": [ "link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "link" ], "type": "alias" }
      ],
      [
       { "params": [ "mkdir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "mkdir" ], "type": "alias" }
      ],
      [
       { "params": [ "setxattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "setxattr" ], "type": "alias" }
      ],
      [
       { "params": [ "open" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "open" ], "type": "alias" }
      ],
      [
       { "params": [ "rename" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "rename" ], "type": "alias" }
      ],
      [
       { "params": [ "rmdir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "rmdir" ], "type": "alias" }
      ],
      [
       { "params": [ "mknod" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "mknod" ], "type": "alias" }
      ],
      [
       { "params": [ "setattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "setattr" ], "type": "alias" }
      ],
      [
       { "params": [ "statfs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "statfs" ], "type": "alias" }
      ],
      [
       { "params": [ "setxattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "setxattr" ], "type": "alias" }
      ],
      [
       { "params": [ "sync" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "sync" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "lustre" }
     ]
    }
   ]
  }
 ]
}