{
 "title": "Lustre Details",
 "description": "Lustre details like IOPs and OST usage",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Lustre Metadata",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lustre2",
     "query": "SELECT difference(mean(\"unlink\")) AS \"unlink\", difference(mean(\"close\")) AS \"close\", difference(mean(\"getattr\")) AS \"getattr\", difference(mean(\"getxattr\")) AS \"getxattr\", difference(mean(\"link\")) AS \"link\", difference(mean(\"mkdir\")) AS \"mkdir\", difference(mean(\"setxattr\")) AS \"setxattr\", difference(mean(\"open\")) AS \"open\", difference(mean(\"rename\")) AS \"rename\", difference(mean(\"rmdir\")) AS \"rmdir\", difference(mean(\"mknod\")) AS \"mknod\", difference(mean(\"setattr\")) AS \"setattr\", difference(mean(\"statfs\")) AS \"statfs\", difference(mean(\"setxattr\")) AS \"setxattr\", difference(mean(\"sync\")) AS \"sync\" FROM \"lustre2\" WHERE (\"host\" = 'mds1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unlink" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "unlink" ], "type": "alias" }
      ],
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "close" ], "type": "alias" }
      ],
      [
       { "params": [ "getattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "getattr" ], "type": "alias" }
      ],
      [
       { "params": [ "getxattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "getxattr" ], "type": "alias" }
      ],
      [
       { "params": [ "link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "link" ], "type": "alias" }
      ],
      [
       { "params": [ "mkdir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "mkdir" ], "type": "alias" }
      ],
      [
       { "params": [ "setxattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "setxattr" ], "type": "alias" }
      ],
      [
       { "params": [ "open" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "open" ], "type": "alias" }
      ],
      [
       { "params": [ "rename" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "rename" ], "type": "alias" }
      ],
      [
       { "params": [ "rmdir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "rmdir" ], "type": "alias" }
      ],
      [
       { "params": [ "mknod" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "mknod" ], "type": "alias" }
      ],
      [
       { "params": [ "setattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "setattr" ], "type": "alias" }
      ],
      [
       { "params": [ "statfs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "statfs" ], "type": "alias" }
      ],
      [
       { "params": [ "setxattr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "setxattr" ], "type": "alias" }
      ],
      [
       { "params": [ "sync" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "sync" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "lustre" }
     ]
    }
   ]
  },
  {
   "title": "Scratch OSTs usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"Used\" FROM \"disk\" WHERE (\"fstype\" = 'lustre' AND \"host\" =~ /lustre-oss/) AND $timeFilter GROUP BY time($__interval), \"path\" fill(previous)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "=", "value": "lustre" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/oss(1|2|3|4)$/" }
     ]
    }
   ]
  },
  {
   "title": "Scratch OSTs inodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"inodes_used\") AS \"Used\" FROM \"disk\" WHERE (\"fstype\" = 'lustre' AND \"host\" =~ /lustre-oss/) AND $timeFilter GROUP BY time($__interval), \"path\" fill(none)",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "=", "value": "lustre" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/oss/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "inodes_total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "=", "value": "lustre" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "oss1" }
     ]
    }
   ]
  }
 ]
}