{
 "title": "Lustre Overview",
 "description": "A short overview of a Lustre MDS/OSS servers",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "MDS CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "lustre" }
     ]
    }
   ]
  },
  {
   "title": "MDS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "reads" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "lustre" }
     ]
    }
   ]
  },
  {
   "title": "MDS Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Load1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "lustre" }
     ]
    }
   ]
  },
  {
   "title": "OSS CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\") FROM \"system\" WHERE (\"host\" =~ /lustre-oss/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/oss[1|2|3|4]$/" }
     ]
    }
   ]
  },
  {
   "title": "OSS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lustre2",
     "query": "SELECT difference(mean(\"read_bytes\")) AS \"read_bytes\", difference(mean(\"write_bytes\")) AS \"write_bytes\" FROM \"lustre2\" WHERE (\"host\" =~ /lustre-oss/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "read_bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "write_bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/oss(1|2|3|4)$/" }
     ]
    }
   ]
  },
  {
   "title": "OSS Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load1\") AS \"Load1\" FROM \"system\" WHERE (\"host\" =~ /lustre-oss/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Load1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/oss(1|2|3|4)$/" }
     ]
    }
   ]
  }
 ]
}